# Generated by Django 5.1.4 on 2024-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('website', models.URLField()),
                ('instagram', models.URLField()),
                ('discord', models.URLField()),
                ('first_line', models.CharField(max_length=200)),
                ('second_line', models.CharField(max_length=200)),
                ('third_line', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
            ],
        ),
    ]
