# Generated by Django 5.1.4 on 2024-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='plays_malifaux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='stocks_malifaux',
            field=models.BooleanField(default=False),
        ),
    ]
