# Generated by Django 5.1.4 on 2024-12-20 11:08

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_venue_is_store_venue_plays_malifaux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=tinymce.models.HTMLField(default='TBC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='discord',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='first_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='second_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='third_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
