# Generated by Django 5.1.4 on 2024-12-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_event_venue_description_alter_venue_discord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.venue'),
            preserve_default=False,
        ),
    ]
