# Generated by Django 5.1.4 on 2024-12-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_event_created_at_event_updated_at_venue_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='to',
        ),
    ]
