# Generated by Django 5.1.4 on 2024-12-20 20:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_creator_event_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPaintedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_painted_images', to='website.event')),
            ],
        ),
    ]
