# Generated by Django 5.1.4 on 2024-12-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_event_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestpaintedimage',
            name='description',
        ),
        migrations.AddField(
            model_name='bestpaintedimage',
            name='title',
            field=models.CharField(default='Title', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bestpaintedimage',
            name='painter',
            field=models.CharField(max_length=50),
        ),
    ]
