# Generated by Django 5.1.4 on 2025-01-07 20:25

import cloudinary.models
import django.db.models.deletion
import website.models.mixins.image_preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_images', to='website.event')),
            ],
            bases=(models.Model, website.models.mixins.image_preview.ImagePreviewMixin),
        ),
        migrations.CreateModel(
            name='PrizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_images', to='website.event')),
            ],
            bases=(models.Model, website.models.mixins.image_preview.ImagePreviewMixin),
        ),
        migrations.CreateModel(
            name='SwagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swag_images', to='website.event')),
            ],
            bases=(models.Model, website.models.mixins.image_preview.ImagePreviewMixin),
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='website.event')),
            ],
            bases=(models.Model, website.models.mixins.image_preview.ImagePreviewMixin),
        ),
    ]
