# Generated by Django 5.1.4 on 2025-01-11 23:50

import django.db.models.deletion
import tinymce.models
import website.models.mixins.image_preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_playimage_prizeimage_swagimage_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, unique=True)),
                ('tab_title', models.CharField(max_length=30)),
                ('page_title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
            bases=(models.Model, website.models.mixins.image_preview.ImagePreviewMixin),
        ),
        migrations.CreateModel(
            name='PageContentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('content', tinymce.models.HTMLField()),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_content_items', to='website.page')),
            ],
            options={
                'unique_together': {('page', 'key')},
            },
            bases=(models.Model, website.models.mixins.image_preview.ImagePreviewMixin),
        ),
    ]
