# Generated by Django 5.1.4 on 2025-01-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_page_pagecontenttext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecontenttext',
            old_name='content',
            new_name='html',
        ),
    ]
