# Generated by Django 5.1.4 on 2025-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_content_pagecontenttext_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='tab_title',
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='CHANGE ME', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
