# Generated by Django 5.1.4 on 2025-01-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_page_page_title_remove_page_tab_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.IntegerField(default=3),
        ),
    ]
