# Generated by Django 5.1.4 on 2025-01-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_event_days_event_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ruleset',
            field=models.TextField(default='GG4, singles', max_length=200),
        ),
    ]
