# Generated by Django 5.1.4 on 2025-01-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_event_ruleset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ruleset',
        ),
        migrations.AddField(
            model_name='event',
            name='variant',
            field=models.TextField(default='GG4, Singles', help_text="This should be a short description of the tournament setup. It will be inserted into the sentence 'X rounds of WHAT_YOU_ENTER_HERE' and should not be a sentence on its own. E.g. 'Singles, Bans 1, No Repeating Strategies' or 'Singles, GG4", max_length=100),
        ),
    ]
